aString = "Alphabet!"
print("String Operations on '%s'" % aString)
print("")
print("Length")
print(len(aString))
print("")
print("Index of 'a' (case sensitive)")
print(aString.index("a"))
print("")
print("Counting 'l'")
print(aString.count("l"))
print("")
print("Characters from 3-7")
print(aString[3:7])
print("")
print("Skip one character")
print(aString[3:7:2])
print("")
bString = "Hello World!"
print(bString[3:7])
print(bString[3:7:1])
print("")
print("Reverse")
print(aString[::-1])
print("")
print("Changing case")
print(aString.upper())
print(aString.lower())
print(aString)
print("")
print(aString.startswith("Al"))
print(aString.endswith("GAH!"))
